config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :albums
  resources :artists
  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :playlists do
    member do
      post 'add_track'
      delete 'remove_track/:track_id', action: :remove_track, as: :remove_track
    end
  end
  
  # Defines the root path route ("/")
  root "home#index"
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
  has_one_attached :audio_file

  has_many :playlist_tracks, dependent: :destroy
  has_many :playlists, through: :playlist_tracks

  def artist
    album.artist
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track, only: %i[ show edit update destroy ]

  # GET /tracks or /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1 or /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks or /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: "Track was successfully created." }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1 or /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: "Track was successfully updated." }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1 or /tracks/1.json
  def destroy
    @track.destroy!

    respond_to do |format|
      format.html { redirect_to tracks_path, status: :see_other, notice: "Track was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:title, :album_id, :audio_file)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true, html: { multipart: true }) do |form| %>
  <% if track.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :album_id, style: "display: block" %>
    <%= form.text_field :album_id %>
  </div>

  <div class="mb-3">
  <%= form.label :audio_file %>
  <%= form.file_field :audio_file, direct_upload: true, class: "form-control" %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<div id="<%= dom_id track %>">
  <p>
    <strong>Title:</strong>
    <%= track.title %>
  </p>

  <p>
    <strong>Album:</strong>
    <%= track.album_id %>
  </p>

</div>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Show this track", @track %> |
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/index.html.erb
<h1>Tracks</h1>

<%= link_to 'New Tracks', new_album_path, class: "btn btn-primary mb-3" %>

<div class="list-group">
  <% @tracks.each do |track| %>
    <a href="<%= track_path(track) %>" class="list-group-item list-group-item-action">
      <strong><%= track.title %></strong><br>
      <small><%= truncate(track.album.title, length: 100) %></small>
    </a>
  <% end %>
</div>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @track %>
<% if @track.audio_file.attached? %>
  <audio controls class="w-100 mt-3">
    <source src="<%= url_for(@track.audio_file) %>" type="<%= @track.audio_file.content_type %>">
    Your browser does not support the audio element.
  </audio>
<% end %>

<div>
  <%= link_to "Edit this track", edit_track_path(@track) %> |
  <%= link_to "Back to tracks", tracks_path %>

  <%= button_to "Destroy this track", @track, method: :delete %>
</div>