config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :albums
  resources :artists
  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :playlists do
    member do
      post 'add_track'
      delete 'remove_track/:track_id', action: :remove_track, as: :remove_track
    end
  end
  
  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniSpotify</title>
  <!-- Add this inside <head> -->
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap", media: "all" %>


 
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <!-- Bootstrap 5 CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark custom-navbar">
  <div class="container">
    <%= link_to "Mini-Spotify 🎧", root_path, class: "navbar-brand fw-bold" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Playlists", playlists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Tracks", tracks_path, class: "nav-link" %>
          </li>
          </li>
          <li class="nav-item">
            <%= link_to "Albums", albums_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-gradient ms-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  <%= yield %>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>